FROM ubuntu:20.04


RUN apt-get update
RUN apt-get -y install git
RUN apt-get -y install wget

RUN apt -y install build-essential
RUN apt-get -y install manpages-dev
RUN apt -y install python3-pip
RUN apt-get -y install python